name: Deploy client to GH Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - '.github/workflows/deploy-client.yml'
  workflow_dispatch: {}   # allow manual runs from the Actions 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # Make base path '/<repo>/' so assets resolve on Pages
      - name: Compute BASE_PATH
        run: echo "BASE_PATH=/" >> $GITHUB_ENV

      # Provide the API URL at build time
      - name: Write .env.production
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > client/.env.production

      - name: Build client
        run: |
          cd client
          npm install
          npm run build
          # SPA fallback so React Router refreshes don't 404
          cp dist/index.html dist/404.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: client/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
